// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_sessions.sql

package db

import (
	"context"
)

const deleteAuthSessions = `-- name: DeleteAuthSessions :exec
DELETE FROM auth_sessions WHERE user_id = $1
`

func (q *Queries) DeleteAuthSessions(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteAuthSessions, userID)
	return err
}

const getAuthSession = `-- name: GetAuthSession :one
SELECT id, user_id, refresh_hash, expires_at FROM auth_sessions WHERE id = $1 AND expires_at > NOW()
`

func (q *Queries) GetAuthSession(ctx context.Context, id string) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getAuthSession, id)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshHash,
		&i.ExpiresAt,
	)
	return i, err
}
