// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_verification_codes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeEmailVerificationCode = `-- name: ConsumeEmailVerificationCode :one
WITH consumed AS (
  UPDATE email_verification_codes SET used_at = NOW()
  WHERE user_id = $1::bigint
    AND code_hash = $2::char(64)
    AND used_at IS NULL AND expires_at > NOW()
  RETURNING user_id
)
UPDATE users SET email_verified_at = NOW(), updated_at = NOW()
WHERE id = (SELECT user_id FROM consumed)
RETURNING id
`

type ConsumeEmailVerificationCodeParams struct {
	UserID   int64
	CodeHash string
}

func (q *Queries) ConsumeEmailVerificationCode(ctx context.Context, arg ConsumeEmailVerificationCodeParams) (int64, error) {
	row := q.db.QueryRow(ctx, consumeEmailVerificationCode, arg.UserID, arg.CodeHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createEmailVerificationCode = `-- name: CreateEmailVerificationCode :exec
WITH revoked AS (
  UPDATE email_verification_codes SET used_at = NOW()
  WHERE user_id = $1::bigint AND used_at IS NULL
  RETURNING id
)
INSERT INTO email_verification_codes (user_id, code_hash, expires_at)
SELECT $1::bigint, $2::char(64), $3::timestamptz
FROM (SELECT COUNT(*) FROM revoked) AS revocation_complete
ON CONFLICT DO NOTHING
`

type CreateEmailVerificationCodeParams struct {
	UserID    int64
	CodeHash  string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateEmailVerificationCode(ctx context.Context, arg CreateEmailVerificationCodeParams) error {
	_, err := q.db.Exec(ctx, createEmailVerificationCode, arg.UserID, arg.CodeHash, arg.ExpiresAt)
	return err
}
