// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_verifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeEmailVerification = `-- name: ConsumeEmailVerification :execrows
UPDATE email_verifications
SET consumed_at = NOW()
WHERE id = $1 AND consumed_at IS NULL
`

func (q *Queries) ConsumeEmailVerification(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, consumeEmailVerification, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createEmailVerification = `-- name: CreateEmailVerification :one
INSERT INTO email_verifications (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, consumed_at, created_at
`

type CreateEmailVerificationParams struct {
	UserID    int64
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, createEmailVerification, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const expirePendingEmailVerifications = `-- name: ExpirePendingEmailVerifications :exec
UPDATE email_verifications
SET consumed_at = NOW()
WHERE user_id = $1 AND consumed_at IS NULL
`

// Invalidates any earlier unconsumed links for the user so only the most
// recently sent one (register or resend) can still be used.
func (q *Queries) ExpirePendingEmailVerifications(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, expirePendingEmailVerifications, userID)
	return err
}

const getEmailVerificationByID = `-- name: GetEmailVerificationByID :one
SELECT id, user_id, token_hash, expires_at, consumed_at, created_at FROM email_verifications
WHERE id = $1
`

func (q *Queries) GetEmailVerificationByID(ctx context.Context, id pgtype.UUID) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationByID, id)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markUserEmailVerified = `-- name: MarkUserEmailVerified :execrows
UPDATE users
SET email_verified_at = NOW(), updated_at = NOW()
WHERE id = $1 AND email_verified_at IS NULL
`

func (q *Queries) MarkUserEmailVerified(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, markUserEmailVerified, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
