// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_reset_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumePasswordResetToken = `-- name: ConsumePasswordResetToken :one
UPDATE password_reset_tokens
SET used_at = NOW()
WHERE token_hash = $1::char(64)
  AND used_at IS NULL
  AND expires_at > NOW()
RETURNING user_id
`

// The update is atomic, so a link can only be consumed once.
func (q *Queries) ConsumePasswordResetToken(ctx context.Context, tokenHash string) (int64, error) {
	row := q.db.QueryRow(ctx, consumePasswordResetToken, tokenHash)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :exec
WITH revoked AS (
  UPDATE password_reset_tokens
  SET used_at = NOW()
  WHERE user_id = $1::bigint
    AND used_at IS NULL
)
INSERT INTO password_reset_tokens (user_id, token_hash, expires_at)
VALUES (
  $1::bigint,
  $2::char(64),
  $3::timestamptz
)
ON CONFLICT DO NOTHING
`

type CreatePasswordResetTokenParams struct {
	UserID    int64
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

// Reissuing a token invalidates all previous unused links for this account.
func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, createPasswordResetToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}
