// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_resets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumePasswordReset = `-- name: ConsumePasswordReset :execrows
UPDATE password_resets
SET consumed_at = NOW()
WHERE id = $1 AND consumed_at IS NULL
`

func (q *Queries) ConsumePasswordReset(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, consumePasswordReset, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createPasswordReset = `-- name: CreatePasswordReset :one
INSERT INTO password_resets (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, consumed_at, created_at
`

type CreatePasswordResetParams struct {
	UserID    int64
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, createPasswordReset, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const expirePendingPasswordResets = `-- name: ExpirePendingPasswordResets :exec
UPDATE password_resets
SET consumed_at = NOW()
WHERE user_id = $1 AND consumed_at IS NULL
`

// Invalidates any earlier unconsumed links for the user so only the most
// recently requested one can still be used.
func (q *Queries) ExpirePendingPasswordResets(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, expirePendingPasswordResets, userID)
	return err
}

const getPasswordResetByID = `-- name: GetPasswordResetByID :one
SELECT id, user_id, token_hash, expires_at, consumed_at, created_at FROM password_resets
WHERE id = $1
`

func (q *Queries) GetPasswordResetByID(ctx context.Context, id pgtype.UUID) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, getPasswordResetByID, id)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}
