// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pending_registrations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumePendingRegistration = `-- name: ConsumePendingRegistration :one
DELETE FROM pending_registrations
WHERE email = $1::text
  AND code_hash = $2::char(64)
  AND expires_at > NOW()
RETURNING email, password_hash, nickname
`

type ConsumePendingRegistrationParams struct {
	Email    string
	CodeHash string
}

type ConsumePendingRegistrationRow struct {
	Email        string
	PasswordHash string
	Nickname     pgtype.Text
}

func (q *Queries) ConsumePendingRegistration(ctx context.Context, arg ConsumePendingRegistrationParams) (ConsumePendingRegistrationRow, error) {
	row := q.db.QueryRow(ctx, consumePendingRegistration, arg.Email, arg.CodeHash)
	var i ConsumePendingRegistrationRow
	err := row.Scan(&i.Email, &i.PasswordHash, &i.Nickname)
	return i, err
}

const createPendingRegistration = `-- name: CreatePendingRegistration :exec
INSERT INTO pending_registrations (email, password_hash, nickname, code_hash, expires_at)
VALUES (
  $1::text,
  $2::text,
  $3::text,
  $4::char(64),
  $5::timestamptz
)
ON CONFLICT (email) DO UPDATE SET
  password_hash = EXCLUDED.password_hash,
  nickname = EXCLUDED.nickname,
  code_hash = EXCLUDED.code_hash,
  expires_at = EXCLUDED.expires_at,
  updated_at = NOW()
`

type CreatePendingRegistrationParams struct {
	Email        string
	PasswordHash string
	Nickname     pgtype.Text
	CodeHash     string
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) CreatePendingRegistration(ctx context.Context, arg CreatePendingRegistrationParams) error {
	_, err := q.db.Exec(ctx, createPendingRegistration,
		arg.Email,
		arg.PasswordHash,
		arg.Nickname,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	return err
}

const refreshPendingRegistrationCode = `-- name: RefreshPendingRegistrationCode :one
UPDATE pending_registrations
SET code_hash = $1::char(64),
    expires_at = $2::timestamptz,
    updated_at = NOW()
WHERE email = $3::text
RETURNING email
`

type RefreshPendingRegistrationCodeParams struct {
	CodeHash  string
	ExpiresAt pgtype.Timestamptz
	Email     string
}

func (q *Queries) RefreshPendingRegistrationCode(ctx context.Context, arg RefreshPendingRegistrationCodeParams) (string, error) {
	row := q.db.QueryRow(ctx, refreshPendingRegistrationCode, arg.CodeHash, arg.ExpiresAt, arg.Email)
	var email string
	err := row.Scan(&email)
	return email, err
}
