// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pending_registrations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumePendingRegistration = `-- name: ConsumePendingRegistration :one
DELETE FROM pending_registrations
WHERE email = $1::text
  AND challenge_hash = $2::text
  AND code_hash = $3::char(64)
  AND expires_at > NOW()
RETURNING email, password_hash, nickname
`

type ConsumePendingRegistrationParams struct {
	Email         string
	ChallengeHash string
	CodeHash      string
}

type ConsumePendingRegistrationRow struct {
	Email        string
	PasswordHash string
	Nickname     pgtype.Text
}

func (q *Queries) ConsumePendingRegistration(ctx context.Context, arg ConsumePendingRegistrationParams) (ConsumePendingRegistrationRow, error) {
	row := q.db.QueryRow(ctx, consumePendingRegistration, arg.Email, arg.ChallengeHash, arg.CodeHash)
	var i ConsumePendingRegistrationRow
	err := row.Scan(&i.Email, &i.PasswordHash, &i.Nickname)
	return i, err
}

const createPendingRegistration = `-- name: CreatePendingRegistration :exec
INSERT INTO pending_registrations (email, password_hash, nickname, code_hash, expires_at, challenge_hash)
VALUES (
  $1::text,
  $2::text,
  $3::text,
  $4::char(64),
  $5::timestamptz,
  $6::text
)
ON CONFLICT (challenge_hash) DO NOTHING
`

type CreatePendingRegistrationParams struct {
	Email         string
	PasswordHash  string
	Nickname      pgtype.Text
	CodeHash      string
	ExpiresAt     pgtype.Timestamptz
	ChallengeHash string
}

func (q *Queries) CreatePendingRegistration(ctx context.Context, arg CreatePendingRegistrationParams) error {
	_, err := q.db.Exec(ctx, createPendingRegistration,
		arg.Email,
		arg.PasswordHash,
		arg.Nickname,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.ChallengeHash,
	)
	return err
}

const refreshPendingRegistrationCode = `-- name: RefreshPendingRegistrationCode :one
UPDATE pending_registrations
SET code_hash = $1::char(64),
    expires_at = $2::timestamptz,
    updated_at = NOW()
WHERE email = $3::text
  AND challenge_hash = $4::text
  AND expires_at > NOW()
RETURNING email
`

type RefreshPendingRegistrationCodeParams struct {
	CodeHash      string
	ExpiresAt     pgtype.Timestamptz
	Email         string
	ChallengeHash string
}

func (q *Queries) RefreshPendingRegistrationCode(ctx context.Context, arg RefreshPendingRegistrationCodeParams) (string, error) {
	row := q.db.QueryRow(ctx, refreshPendingRegistrationCode,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.Email,
		arg.ChallengeHash,
	)
	var email string
	err := row.Scan(&email)
	return email, err
}
