// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearExpiredProblemReportAttachments = `-- name: ClearExpiredProblemReportAttachments :execrows
UPDATE problem_reports
SET attachment = NULL,
    attachment_mime = NULL,
    attachment_filename = NULL,
    attachment_size = NULL
WHERE attachment IS NOT NULL
  AND attachment_expires_at <= CURRENT_TIMESTAMP
`

func (q *Queries) ClearExpiredProblemReportAttachments(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, clearExpiredProblemReportAttachments)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createProblemReport = `-- name: CreateProblemReport :one
INSERT INTO problem_reports (
    user_id,
    schema_version,
    description,
    diagnostics,
    fingerprint,
    release_version,
    commit_sha,
    source_request_id,
    attachment,
    attachment_mime,
    attachment_filename,
    attachment_size
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
RETURNING id::text AS report_id, created_at
`

type CreateProblemReportParams struct {
	UserID             int64
	SchemaVersion      int16
	Description        string
	Diagnostics        []byte
	Fingerprint        string
	ReleaseVersion     pgtype.Text
	CommitSha          pgtype.Text
	SourceRequestID    string
	Attachment         []byte
	AttachmentMime     pgtype.Text
	AttachmentFilename pgtype.Text
	AttachmentSize     pgtype.Int4
}

type CreateProblemReportRow struct {
	ReportID  string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateProblemReport(ctx context.Context, arg CreateProblemReportParams) (CreateProblemReportRow, error) {
	row := q.db.QueryRow(ctx, createProblemReport,
		arg.UserID,
		arg.SchemaVersion,
		arg.Description,
		arg.Diagnostics,
		arg.Fingerprint,
		arg.ReleaseVersion,
		arg.CommitSha,
		arg.SourceRequestID,
		arg.Attachment,
		arg.AttachmentMime,
		arg.AttachmentFilename,
		arg.AttachmentSize,
	)
	var i CreateProblemReportRow
	err := row.Scan(&i.ReportID, &i.CreatedAt)
	return i, err
}

const deleteExpiredProblemReports = `-- name: DeleteExpiredProblemReports :execrows
DELETE FROM problem_reports
WHERE expires_at <= CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredProblemReports(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredProblemReports)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
