// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roadmap.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearRoadmapTarget = `-- name: ClearRoadmapTarget :exec
UPDATE users
SET target_company = NULL, interview_date = NULL, target_topics = '{}', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ClearRoadmapTarget(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, clearRoadmapTarget, id)
	return err
}

const deleteUserRoadmapConfig = `-- name: DeleteUserRoadmapConfig :exec
DELETE FROM user_roadmap_configs WHERE user_id = $1
`

func (q *Queries) DeleteUserRoadmapConfig(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserRoadmapConfig, userID)
	return err
}

const deleteUserRoadmapPlanItems = `-- name: DeleteUserRoadmapPlanItems :exec
DELETE FROM user_roadmap_plan_items WHERE user_id = $1
`

func (q *Queries) DeleteUserRoadmapPlanItems(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserRoadmapPlanItems, userID)
	return err
}

const getRoadmapUserTarget = `-- name: GetRoadmapUserTarget :one
SELECT target_company, interview_date, target_topics
FROM users
WHERE id = $1
`

type GetRoadmapUserTargetRow struct {
	TargetCompany pgtype.Text
	InterviewDate pgtype.Timestamptz
	TargetTopics  []string
}

func (q *Queries) GetRoadmapUserTarget(ctx context.Context, id int64) (GetRoadmapUserTargetRow, error) {
	row := q.db.QueryRow(ctx, getRoadmapUserTarget, id)
	var i GetRoadmapUserTargetRow
	err := row.Scan(&i.TargetCompany, &i.InterviewDate, &i.TargetTopics)
	return i, err
}

const getUserRoadmapConfig = `-- name: GetUserRoadmapConfig :one
SELECT user_id, company_code, priority_mode, horizon_weeks, weekly_capacity,
       algorithm_version, source, generated_at
FROM user_roadmap_configs
WHERE user_id = $1
`

type GetUserRoadmapConfigRow struct {
	UserID           int64
	CompanyCode      pgtype.Text
	PriorityMode     string
	HorizonWeeks     int32
	WeeklyCapacity   int32
	AlgorithmVersion int32
	Source           string
	GeneratedAt      pgtype.Timestamptz
}

func (q *Queries) GetUserRoadmapConfig(ctx context.Context, userID int64) (GetUserRoadmapConfigRow, error) {
	row := q.db.QueryRow(ctx, getUserRoadmapConfig, userID)
	var i GetUserRoadmapConfigRow
	err := row.Scan(
		&i.UserID,
		&i.CompanyCode,
		&i.PriorityMode,
		&i.HorizonWeeks,
		&i.WeeklyCapacity,
		&i.AlgorithmVersion,
		&i.Source,
		&i.GeneratedAt,
	)
	return i, err
}

const insertUserRoadmapPlanItem = `-- name: InsertUserRoadmapPlanItem :exec
INSERT INTO user_roadmap_plan_items (
    user_id, subpattern_id, week_index, position, selected
)
SELECT $1, p.id, $2, $3, $4
FROM patterns p
WHERE p.code = $5 AND p.kind = 'subpattern'
`

type InsertUserRoadmapPlanItemParams struct {
	UserID         int64
	WeekIndex      int32
	Position       int32
	Selected       bool
	SubpatternCode string
}

func (q *Queries) InsertUserRoadmapPlanItem(ctx context.Context, arg InsertUserRoadmapPlanItemParams) error {
	_, err := q.db.Exec(ctx, insertUserRoadmapPlanItem,
		arg.UserID,
		arg.WeekIndex,
		arg.Position,
		arg.Selected,
		arg.SubpatternCode,
	)
	return err
}

const listRoadmapPlanCardProgress = `-- name: ListRoadmapPlanCardProgress :many
SELECT
    sp.code AS subpattern_code,
    COUNT(c.id)::integer AS total_cards,
    COUNT(c.id) FILTER (WHERE rs.last_rating IS NOT NULL)::integer AS reviewed_cards,
    COUNT(c.id) FILTER (WHERE rs.next_review_at <= NOW())::integer AS due_cards
FROM patterns sp
LEFT JOIN cards c
    ON c.pattern_id = sp.id
   AND (c.user_id IS NULL OR c.user_id = $1::bigint)
LEFT JOIN review_schedules rs
    ON rs.card_id = c.id AND rs.user_id = $1::bigint
WHERE sp.code = ANY($2::text[])
GROUP BY sp.code
ORDER BY sp.code
`

type ListRoadmapPlanCardProgressParams struct {
	UserID          int64
	SubpatternCodes []string
}

type ListRoadmapPlanCardProgressRow struct {
	SubpatternCode string
	TotalCards     int32
	ReviewedCards  int32
	DueCards       int32
}

func (q *Queries) ListRoadmapPlanCardProgress(ctx context.Context, arg ListRoadmapPlanCardProgressParams) ([]ListRoadmapPlanCardProgressRow, error) {
	rows, err := q.db.Query(ctx, listRoadmapPlanCardProgress, arg.UserID, arg.SubpatternCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoadmapPlanCardProgressRow
	for rows.Next() {
		var i ListRoadmapPlanCardProgressRow
		if err := rows.Scan(
			&i.SubpatternCode,
			&i.TotalCards,
			&i.ReviewedCards,
			&i.DueCards,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoadmapPlanProblems = `-- name: ListRoadmapPlanProblems :many
WITH ranked AS (
    SELECT
        sp.code AS subpattern_code,
        pr.id,
        pr.title,
        pr.url,
        COALESCE(pr.difficulty, '')::text AS difficulty,
        COALESCE(ps.tier, '')::text AS tier,
        COALESCE(upp.status, 'not_started')::text AS status,
        ROW_NUMBER() OVER (
            PARTITION BY sp.code
            ORDER BY
                CASE ps.tier
                    WHEN 'foundational' THEN 0
                    WHEN 'core' THEN 1
                    WHEN 'advanced' THEN 2
                    ELSE 3
                END,
                CASE LOWER(COALESCE(pr.difficulty, ''))
                    WHEN 'easy' THEN 0
                    WHEN 'medium' THEN 1
                    WHEN 'hard' THEN 2
                    ELSE 3
                END,
                COALESCE(cp.evidence_count, 0) DESC,
                ps.position NULLS LAST,
                pr.id
        ) AS task_rank
    FROM patterns sp
    JOIN problem_subpatterns ps ON ps.subpattern_id = sp.id
    JOIN problems pr ON pr.id = ps.problem_id
    LEFT JOIN user_problem_progress upp
        ON upp.problem_id = pr.id AND upp.user_id = $1::bigint
    LEFT JOIN companies co ON co.code = NULLIF($2::text, '')
    LEFT JOIN company_problems cp
        ON cp.problem_id = pr.id AND cp.company_id = co.id
    WHERE sp.code = ANY($3::text[])
      AND ($2::text = '' OR cp.problem_id IS NOT NULL)
)
SELECT subpattern_code, id, title, url, difficulty, tier, status
FROM ranked
WHERE task_rank <= 3
ORDER BY subpattern_code, task_rank
`

type ListRoadmapPlanProblemsParams struct {
	UserID          int64
	CompanyCode     string
	SubpatternCodes []string
}

type ListRoadmapPlanProblemsRow struct {
	SubpatternCode string
	ID             int64
	Title          string
	Url            string
	Difficulty     string
	Tier           string
	Status         string
}

// Stable, deliberately small task set for every subpattern included in a
// personal plan. The rank does not depend on user progress, so solving a task
// never replaces it with another one and turns the plan into an endless list.
func (q *Queries) ListRoadmapPlanProblems(ctx context.Context, arg ListRoadmapPlanProblemsParams) ([]ListRoadmapPlanProblemsRow, error) {
	rows, err := q.db.Query(ctx, listRoadmapPlanProblems, arg.UserID, arg.CompanyCode, arg.SubpatternCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoadmapPlanProblemsRow
	for rows.Next() {
		var i ListRoadmapPlanProblemsRow
		if err := rows.Scan(
			&i.SubpatternCode,
			&i.ID,
			&i.Title,
			&i.Url,
			&i.Difficulty,
			&i.Tier,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoadmapItems = `-- name: ListUserRoadmapItems :many
SELECT
    ri.position,
    pt.code AS pattern_code,
    pt.name AS pattern_name,
    p.id AS problem_id,
    p.external_id,
    p.external_slug,
    p.title,
    p.url,
    p.difficulty,
    COALESCE(upp.status, 'not_started')::text AS status,
    upp.rating,
    upp.confidence
FROM roadmap_items ri
JOIN patterns pt ON pt.id = ri.pattern_id
JOIN problems p ON p.id = ri.problem_id
LEFT JOIN user_problem_progress upp
    ON upp.problem_id = p.id AND upp.user_id = $2
WHERE ri.roadmap_code = $1
ORDER BY ri.position ASC
`

type ListUserRoadmapItemsParams struct {
	RoadmapCode string
	UserID      int64
}

type ListUserRoadmapItemsRow struct {
	Position     int32
	PatternCode  string
	PatternName  string
	ProblemID    int64
	ExternalID   pgtype.Text
	ExternalSlug string
	Title        string
	Url          string
	Difficulty   pgtype.Text
	Status       string
	Rating       pgtype.Text
	Confidence   pgtype.Int4
}

func (q *Queries) ListUserRoadmapItems(ctx context.Context, arg ListUserRoadmapItemsParams) ([]ListUserRoadmapItemsRow, error) {
	rows, err := q.db.Query(ctx, listUserRoadmapItems, arg.RoadmapCode, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserRoadmapItemsRow
	for rows.Next() {
		var i ListUserRoadmapItemsRow
		if err := rows.Scan(
			&i.Position,
			&i.PatternCode,
			&i.PatternName,
			&i.ProblemID,
			&i.ExternalID,
			&i.ExternalSlug,
			&i.Title,
			&i.Url,
			&i.Difficulty,
			&i.Status,
			&i.Rating,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoadmapPlanItems = `-- name: ListUserRoadmapPlanItems :many
SELECT p.code, p.name, p.position AS taxonomy_position,
       i.week_index, i.position, i.selected
FROM user_roadmap_plan_items i
JOIN patterns p ON p.id = i.subpattern_id
WHERE i.user_id = $1
ORDER BY i.position
`

type ListUserRoadmapPlanItemsRow struct {
	Code             string
	Name             string
	TaxonomyPosition pgtype.Int4
	WeekIndex        int32
	Position         int32
	Selected         bool
}

func (q *Queries) ListUserRoadmapPlanItems(ctx context.Context, userID int64) ([]ListUserRoadmapPlanItemsRow, error) {
	rows, err := q.db.Query(ctx, listUserRoadmapPlanItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserRoadmapPlanItemsRow
	for rows.Next() {
		var i ListUserRoadmapPlanItemsRow
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.TaxonomyPosition,
			&i.WeekIndex,
			&i.Position,
			&i.Selected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRoadmapTarget = `-- name: SetRoadmapTarget :exec
UPDATE users
SET target_company = NULLIF($1::text, ''),
    interview_date = $2::timestamptz,
    target_topics = $3::text[],
    updated_at = NOW()
WHERE id = $4
`

type SetRoadmapTargetParams struct {
	TargetCompany string
	InterviewDate pgtype.Timestamptz
	TargetTopics  []string
	UserID        int64
}

func (q *Queries) SetRoadmapTarget(ctx context.Context, arg SetRoadmapTargetParams) error {
	_, err := q.db.Exec(ctx, setRoadmapTarget,
		arg.TargetCompany,
		arg.InterviewDate,
		arg.TargetTopics,
		arg.UserID,
	)
	return err
}

const upsertUserRoadmapConfig = `-- name: UpsertUserRoadmapConfig :exec
INSERT INTO user_roadmap_configs (
    user_id, company_code, priority_mode, horizon_weeks, weekly_capacity,
    algorithm_version, source, generated_at, updated_at
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7, NOW(), NOW()
)
ON CONFLICT (user_id) DO UPDATE SET
    company_code = EXCLUDED.company_code,
    priority_mode = EXCLUDED.priority_mode,
    horizon_weeks = EXCLUDED.horizon_weeks,
    weekly_capacity = EXCLUDED.weekly_capacity,
    algorithm_version = EXCLUDED.algorithm_version,
    source = EXCLUDED.source,
    generated_at = CASE
        WHEN $8::boolean THEN user_roadmap_configs.generated_at
        ELSE NOW()
    END,
    updated_at = NOW()
`

type UpsertUserRoadmapConfigParams struct {
	UserID           int64
	CompanyCode      pgtype.Text
	PriorityMode     string
	HorizonWeeks     int32
	WeeklyCapacity   int32
	AlgorithmVersion int32
	Source           string
	PreserveProgress bool
}

func (q *Queries) UpsertUserRoadmapConfig(ctx context.Context, arg UpsertUserRoadmapConfigParams) error {
	_, err := q.db.Exec(ctx, upsertUserRoadmapConfig,
		arg.UserID,
		arg.CompanyCode,
		arg.PriorityMode,
		arg.HorizonWeeks,
		arg.WeeklyCapacity,
		arg.AlgorithmVersion,
		arg.Source,
		arg.PreserveProgress,
	)
	return err
}
